index:
    path: /
    controller: App\Controller\DefaultController::index
mesrdv:
    path: /rendez_vous
    controller: App\Controller\DefaultController::mesrdv

rdv_admin_mailer:
    path: /admin/rdv/mailer/{id}
    controller: App\Controller\RendezVousController::admin_mailer
    methods:    GET
